# Generated by Django 4.2.3 on 2023-08-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTickets', '0005_alter_venue_webpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.AlterField(
            model_name='artist',
            name='webpage',
            field=models.URLField(max_length=50),
        ),
    ]
